version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: gh-integration-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: github_integration

volumes:
  mongo-data:
